"""create recurring rules table

Revision ID: a157bb4870e3
Revises: fdaed5992445
Create Date: 2026-09-23 10:09:47.771876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a157bb4870e3'
down_revision: Union[str, None] = 'fdaed5992445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_rules_account_id'), 'recurring_rules', ['account_id'], unique=False)
    op.create_index(op.f('ix_recurring_rules_category_id'), 'recurring_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_recurring_rules_next_run_at'), 'recurring_rules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_recurring_rules_user_id'), 'recurring_rules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_rules_user_id'), table_name='recurring_rules')
    op.drop_index(op.f('ix_recurring_rules_next_run_at'), table_name='recurring_rules')
    op.drop_index(op.f('ix_recurring_rules_category_id'), table_name='recurring_rules')
    op.drop_index(op.f('ix_recurring_rules_account_id'), table_name='recurring_rules')
    op.drop_table('recurring_rules')
    # ### end Alembic commands ###
